export const TASKS = [
  {
    id: 1,
    userId: 3,
    title: 'Task 1 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
  {
    id: 2,
    userId: 3,
    title: 'Task 2 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
  {
    id: 3,
    userId: 1,
    title: 'Task 3 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
  {
    id: 4,
    userId: 2,
    title: 'Task 4 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
  {
    id: 5,
    userId: 2,
    title: 'Task 5 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
  {
    id: 6,
    userId: 2,
    title: 'Task 6 Title',
    description: 'This is a task description',
    date: 'Feb 12th at 6:30pm',
    isCompleted: false,
  },
];
